### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by amangupta2** [amangupta2/nonlocal_gwfluxes#9]

**Comment by TomMelt** [comment]
Hi @amangupta2 , if you add a `pyproject.toml` then you don't need to add a `requirements.txt`. I think `pyproject.toml` is probably better as it can track dependencies (like `requirements.txt`) but also project specific settings.

I will close this anyway as we are moving to the new [Datawave repo](https://github.com/DataWaveProject/nonlocal_gwfluxes/).

Please raise any new issues there.
